# MIT License
# Copyright (C) 2020 Tymko Oleg <olegtymko@yandex.ru> and contributors
# All rights reserved.

name: Линия CI

on: [push]

env:
  BASE_PATH: ./bsl-actions-template

jobs:
  testing:
    runs-on: self-hosted
    steps:
      # Актуализация
      - uses: actions/checkout@v2
      
      # Создание базы данных 1С
      - name: Инициализация базы данных
        run: vrunner init-dev --src ${{ env.BASE_PATH }}/src/cf

      - name: Синтакс-контроль
        run: vrunner syntax-check --settings ./vb-params.json

      - name: Модульное тестирование
        run: vrunner xunit "${{ env.BASE_PATH }}/tests" --settings ./vb-params.json

      - name: Отправка Allure отчета в артефакты
        uses: actions/upload-artifact@master
        with:
          name: allure
          path: build/allure

  sonar-analyze:
    if: github.repository == 'silverbulleters/bsl-actions-template'
    runs-on: ubuntu-18.04
    steps:
      # Актуализация
      - uses: actions/checkout@v2

      # https://stackoverflow.com/questions/58033366/how-to-get-current-branch-within-github-actions
      - name: Извлечение имени текущей ветки
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Установка Sonar-scanner
        uses: warchant/setup-sonar-scanner@v1
        env:
          # отключение безопасности установки, от 2020-10-01
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: Анализ в SonarQube (branch)
        if: github.event_name == 'push'
        run: sonar-scanner
            -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }}
            -Dsonar.host.url=${{ secrets.SONARQUBE_HOST }}
            -Dsonar.branch.name=${{ steps.extract_branch.outputs.branch }}

  allure:
    needs: testing
    runs-on: ubuntu-18.04
    steps:
      - name: Загрузка Allure отчета из артефактов
        uses: actions/download-artifact@master
        with:
          name: allure
          path: build/allure

      - name: Получение истории
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Обработка истории
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: build/allure
          allure_history: allure-history

      - name: Публикация на GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history