# MIT License
# Copyright (C) 2020 Tymko Oleg <olegtymko@yandex.ru> and contributors
# All rights reserved.

name: Подготовка релиза и публикация в хабе
# Только события создания и изменения релиза
on:
    release:
        types: [published, edited]

env:
  BASE_PATH: ./bsl-actions-template

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Сборка CF
        run: |
          mkdir ./build 
          vrunner compile -s ${{ env.BASE_PATH }}/src/cf -o  ${{ env.BASE_PATH }}/build/1Cv8.cf

      - name: Заливка артефактов
        uses: actions/upload-artifact@v2
        with:
          name: 1Cv8
          path: ./build/*.cf
      
      - name: Заливка в релиз
        uses: AButler/upload-release-assets@v1.0
        with:
          files: ./build/*.cf
          repo-token: ${{ secrets.GITHUB_TOKEN }}